name: image_loader
description: Image loader is a helper library to load image from many resorces as[assetFlag, file or network with cach].
  With support with making shape around it as circle or rounded corners
homepage: https://github.com/georgesamirmansour/image_loader.git
version: 1.10.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.1
  gif_view: ^0.4.3
  lottie: ^3.3.1
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assetFlag/
